query user_getUsers(
    $skip: Int
    $take: Int
    $where: UserDtoFilterInput
    $order: [UserDtoSortInput!]
) {
    user_getUsers {
        result(skip: $skip, take: $take, where: $where, order: $order) {
            items {
                plan {
                    title
                    description
                    month
                    price
                    features
                    memberships {
                        startDate
                        endDate
                        paymentAmount
                        userId
                        planId
                        id
                        isDeleted
                        lastModifiedDate
                    }
                    isDeleted
                    id
                }
                user {
                    fullName
                    lastModifiedDate

                    userType
                    phoneNumber
                    address
                    language
                    occupation
                    yearsOfExperience
                    city
                    zipCode
                    memberships {
                        id
                        startDate
                        endDate
                        paymentAmount
                        plan {
                            title
                            id
                        }
                    }
                    gender
                    id
                }
            }
            totalCount
        }
        status
    }
}
