mutation addSkillOfDay($id:Int!){
  skill_addSkillOfDay(skillId:$id){
    status
  }
}

mutation removeSkillOfDay($id:Int!)
{
  skill_removeSkillOfDay(skillId:$id){
    status
  }
}

mutation removeAllSkillOfDay($ids:[Int!]){
  skill_removeAllSkillOfDay(skillIds:$ids) {
    status
  }
}