query getDashboard {
    user_getReportBoxes {
        result {
            totalSkills
            totalCourses
            totalUsers
            totalJobs
        }
        status
    }
    user_getTopUsers {
        result(take: 4) {
            items {
                firstName
                lastName
                pictureUrl
                point
            }
        }
        status
    }
    skill_getSkills {
        result(where: { isToday: { eq: true } }, take: 5) {
            items {
                title
                iconUrl
                skillCategory {
                    title
                }
            }
        }
        status
    }
    report_getChartViewApp{
      result{
        items{
          timeStamp
          total
        }
      }
      status
    }
  	
}

query getSkills($take:Int,$skip:Int,$where:SkillFilterInput,$order:[SkillSortInput!]){
  skill_getSkills{
    result(take:$take,skip:$skip,where:$where,order:$order){
      items{id title  iconUrl isToday isToday createdDate skillCategory{title}}
      pageInfo{hasNextPage hasPreviousPage}
      totalCount
    }
    status
  }
}