query GetAllProducts(
    $skip: Int
    $take: Int
    $where: ProductsFilterInput
    $order: [ProductsSortInput!]
) {
    product_getProducts {
        result(skip: $skip, take: $take, where: $where, order: $order) {
            items {
                name
                description
                photoUrl
                otherMediaUrl
                price
                colors
                exerciseProducts {
                    id
                }
                requestProducts {
                    count
                }
                id
                isDeleted
                lastModifiedDate
            }
            pageInfo {
                hasNextPage
                hasPreviousPage
            }
            totalCount
        }
        status
    }
}
