mutation createLesson($input: LessonInput) {
    lesson_addLesson(input: $input) {
        result {
            id
        }
        status
    }
}

mutation updateLesson($id: Int!, $input: LessonInput!) {
    lesson_updateLesson(id: $id, input: $input) {
        status
    }
}

mutation deleteLesson($id: Int!) {
    lesson_deleteLesson(id: $id) {
        status
    }
}

mutation createTopic($input: TopicInput) {
    topic_addTopic(input: $input) {
        status
        result {
            id
        }
    }
}

mutation updateTopic($id: Int!, $input: TopicInput!) {
    topic_updateTopic(id: $id, input: $input) {
        status
    }
}

mutation deleteTopic($id: Int!) {
    topic_deleteTopic(id: $id) {
        status
    }
}

mutation addCatalog($input: SkillCategoryInput) {
    skillCategory_addSkillCategory(input: $input) {
        result {
            rate
            comments {
                status
            }
            lessons {
                id
            }
            createdDate
            iconUrl
            id
        }
        status
    }
}

mutation createSkillQuestion($input: SkillQuestionInput!) {
    skillQuestion_addQuestion(input: $input) {
        result {
            id
        }
        status
    }
}

mutation updateSkillQuestion($id: Int!, $input: SkillQuestionInput!) {
    skillQuestion_updateQuestion(id: $id, input: $input) {
        status
    }
}

mutation deleteSkillQuestion($id: Int!) {
    skillQuestion_deleteQuestion(id: $id) {
        status
    }
}

mutation createSkill($input: SkillInput) {
    skill_addSkill(input: $input) {
        result {
            id
        }
        status
    }
}

mutation updateCatalogSkill($id: Int!, $input: SkillInput!) {
    skill_updateSkill(id: $id, input: $input) {
        status
    }
}
