query category_getCategories(
    $skip: Int
    $take: Int
    $where: CategoriesFilterInput
    $order: [CategoriesSortInput!]
) {
    category_getCategories {
        result(skip: $skip, take: $take, where: $where, order: $order) {
            items {
                id
                name
                isDeleted
                lastModifiedDate
                createdDate
                subCategories {
                    name
                    categoryId
                    id
                    isDeleted
                    lastModifiedDate
                }
            }
            pageInfo {
                hasNextPage
                hasPreviousPage
            }
            totalCount
        }
        status
    }
}
