mutation message_createMessage($messageInput: MessageInput) {
    message_createMessage(messageInput: $messageInput) {
        status
        result {
            senderId
            text
            conversationId
            createdAt
            messageType
            photoUrl
        }
    }
}