query message_getUserMessages(
    $skip: Int
    $take: Int
    $where: ConversationsFilterInput
    $order: [ConversationsSortInput!]
) {
    message_getAllMessages {
        result(skip: $skip, take: $take, where: $where, order: $order) {
            items {
                subject
                id
                latestMessageDate
                messages {
                    photoUrl
                    messageType
                    text
                }
                firstUser {
                    firstName
                    lastName
                    id
                    pictureUrl
                    email
                    cVFileUrl
                }
                firstUnreadCount
            }
            totalCount
            pageInfo {
                hasNextPage
            }
        }
        status
    }
}

query message_getConversation(
    $conversationId: Int!
    $skip: Int
    $take: Int
    $where: MessagesFilterInput
    $order: [MessagesSortInput!]
) {
    message_getConversation(conversationId: $conversationId) {
        result(skip: $skip, take: $take, where: $where, order: $order) {
            items {
                senderId
                text
                conversationId
                createdAt
                messageType
                photoUrl
            }
            totalCount
            pageInfo {
                hasNextPage
            }
        }
        status
    }
}
