query message_getUserMessages(
    $skip: Int
    $take: Int
    $where: ConversationDtoFilterInput
    $order: [ConversationDtoSortInput!]
) {
    message_getUserMessages {
        result(skip: $skip, take: $take, where: $where, order: $order) {
            items {
                subject
                conversationId
                user {
                    firstName
                    lastName
                    id
                    pictureUrl
                }
                unreadCount
            }
            totalCount
        }
        status
    }
}

query message_getConversation(
    $conversationId: Int!
    $skip: Int
    $take: Int
    $where: MessagesFilterInput
    $order: [MessagesSortInput!]
) {
    message_getConversation(conversationId: $conversationId) {
        result(skip: $skip, take: $take, where: $where, order: $order) {
            items {
                senderId
                text
                conversationId
                createdAt
                messageType
                photoUrl
            }
            totalCount
        }
        status
    }
}
