subscription messageAdded($userId: Int!) {
    messageAdded(userId: $userId) {
        id
        text
        messageType
        photoUrl
        createdAt
        conversationId
        senderId
        sender {
            id
            firstName
            lastName
            pictureUrl
            email
        }
    }
}
