query getJobs($where: JobFilterInput, $take: Int, $skip: Int) {
    job_getJobs {
        result(where: $where, take: $take, skip: $skip) {
            items {
                company {
                    title
                    iconUrl
                }
                status
                title
                country
                city
                jobType
                experienceLevel
                createdDate
            }
            pageInfo {
                hasNextPage
            }
            totalCount
        }
        status
    }
}
