query getJobs($where: JobFilterInput, $take: Int, $skip: Int) {
    job_getJobs {
        result(where: $where, take: $take, skip: $skip) {
            items {
                id
                company {
                    title
                    iconUrl
                }
                status
                title
                country
                city
                jobType
                experienceLevel
                createdDate
            }
            pageInfo {
                hasNextPage
            }
            totalCount
        }
        status
    }
}

query getJob($id:Int!){
  job_getJob(jobId:$id){
    result{
      id,
      title,
      jobType,
      experienceLevel,
      education,
      salary,
      country,
      city,
      description,
      jobCategory{
        id
        title,
      }
      company{
        id,
        title,
        iconUrl
      }
      
    }
    status
  }
  jobSkill_getJobSkills{
    result(where:{jobId:{eq:$id}}){
      items{
        skill{title iconUrl id}
      }
    }
    status
  }
}

query jobRequestGetJobRequests(
    $skip: Int
    $take: Int
    $where: JobRequestFilterInput
    $order: [JobRequestSortInput!]
) {
    jobRequest_getJobRequests {
        status
        result(skip: $skip, take: $take, where: $where, order: $order) {
            items {
                user {
                    firstName
                    lastName
                    pictureUrl
                    email
                }
                jobId
                userId
                cVFileUrl
                id
                createdDate
                status
            }
            pageInfo {
                hasNextPage
                hasPreviousPage
            }
            totalCount
        }
    }
}
