mutation changeUserActiveStatus($id: Int!) {
    user_suspendAccount(userId: $id) {
        status
    }
}

mutation unSuspendUser($id: Int!) {
    user_resumeAccount(userId: $id) {
        status
    }
}

mutation createAdmin($input:CreateAdminInput!){
  user_createAdmin(input:$input){
    status
  }
}