query getCurrentUser {
    user_login {
        result {
            firstName
            lastName
            id
            userType
            userRoles {
                role {
                    id
                    title
                }
            }
        }
        status
    }
}

query getUsers($take: Int, $skip: Int, $where: UserFilterInput) {
    user_getUsers {
        result(skip: $skip, take: $take, where: $where) {
            items {
                firstName
                lastName
                pictureUrl
                phoneNumber
                email
                activeStatus
            }
        }
    }
}
