query getCurrentUser {
    user_login {
        result {
            firstName
            lastName
            id
            userType
            userRoles {
                role {
                    id
                    title
                }
            }
        }
        status
    }
}

query getAllUsers($take: Int, $skip: Int, $where: UserFilterInput, $order: [UserSortInput!]) {
    user_getUsers {
        result(skip: $skip, take: $take, where: $where, order: $order) {
            items {
                id
                firstName
                lastName
                pictureUrl
                phoneNumber
                email
                activeStatus
              	userRoles{role{id,title}},
              	userType
            }
            pageInfo {
                hasNextPage
            }
            totalCount
        }
        status
    }
}
