query getCurrentUser{
    user_login {
        result {
            userType
            userRoles {
                role {
                    id
                    title
                }
            }
        }
        status
    }
}